# Site settings
title: Nathan Winant
email: nw@exegetic.net
description: > # this means to ignore newlines until "baseurl:"
  Code, food, things, and stuff. Mostly things and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://exegetic.net" # the base hostname & protocol for your site

# Social
twitter_username: _nwinant
github_username:  nwinant
linkedin_username: nathanwinant

# Build settings
markdown: kramdown
